[fedora]
#localhost      ansible_connection=local ansible_user=wayne
#bruno           ansible_connection=ssh ansible_user=ansible
#homer          ansible_connection=ssh ansible_user=ansible
elroy           ansible_connection=ssh ansible_user=ansible

[fedora:vars]
ansible_ssh_common_args= '-o "SetEnv TERM=dumb"' 